// Generated by CoffeeScript 1.7.1
var SpaceDerp, getTime;

SpaceDerp = require('../scripts/spacederp');

getTime = function() {
  return 100;
};

exports.SpaceTest = {
  'travelling takes fuel and time and supplies': function(test) {
    var eta, galaxy, location, playerData, space, _ref;
    playerData = {
      travel: {
        location: 'derpbase 1',
        eta: null
      },
      ship: {
        speed: 3,
        lights_per_ton: 4,
        crew: 8,
        cargo: {
          max: 100,
          fuel: 30,
          supplies: 40
        }
      }
    };
    galaxy = {};
    galaxy['derpbase 1'] = {
      location: {
        x: 0,
        y: 4
      }
    };
    galaxy['lol asteroids'] = {
      location: {
        x: 9,
        y: 4
      }
    };
    space = new SpaceDerp(galaxy, 5, getTime);
    _ref = space.travel(playerData, 'lol asteroids').travel, location = _ref.location, eta = _ref.eta;
    test.equals(location, 'lol asteroids');
    test.equals(eta, 100 + (3 * 5));
    return test.done();
  }
};
